In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
print(arr.dtype)

int32


In [4]:
arr2 = np.array([1,2,3,4,5],dtype=np.int16)
arr2

array([1, 2, 3, 4, 5], dtype=int16)

**Zero ones arange random.rand linspace

In [5]:
Z=np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [6]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ran=np.random.rand(4)
ran


array([0.95674426, 0.01381393, 0.61869048, 0.00691286])

In [8]:
ln=np.linspace(0,100,10)
ln


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [9]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
z1=np.zeros([5,5])
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
o1=np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
r1=np.random.rand(4,5)
r1

array([[0.85555305, 0.19447731, 0.22607682, 0.43635831, 0.57861008],
       [0.79365381, 0.71887054, 0.09036442, 0.4567373 , 0.99687061],
       [0.82651684, 0.31849946, 0.67135564, 0.24824824, 0.29938001],
       [0.57868862, 0.46256834, 0.75009453, 0.58519901, 0.0691529 ]])

In [14]:
ar
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(ar.size)

10


In [18]:
print(ar2.size)

9


In [19]:
print(ar.shape)

(10,)


**Operations in Array
Copy
Sort
Reshape

In [20]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
ar3[1,2]=12
ar3[0,1]=15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [22]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [23]:
ar3.sum()

64

In [24]:
ar3.sum(axis=0)

array([12, 16, 36])

In [25]:
ar4=np.random.rand(99)
ar4

array([0.63616123, 0.95400131, 0.15920392, 0.36337535, 0.83940224,
       0.8281249 , 0.59077329, 0.86857736, 0.2743712 , 0.25314867,
       0.55970299, 0.42611381, 0.48412176, 0.51400368, 0.80154949,
       0.31432764, 0.11968132, 0.9501315 , 0.59829699, 0.27849779,
       0.61717479, 0.20989132, 0.58311137, 0.64338021, 0.50683797,
       0.68920955, 0.87775963, 0.07864126, 0.09897208, 0.24169293,
       0.01741263, 0.41230484, 0.42909468, 0.62298335, 0.79916845,
       0.90373792, 0.2648025 , 0.59712596, 0.05970648, 0.13267791,
       0.45029531, 0.08409991, 0.99731244, 0.43566161, 0.64825767,
       0.39501889, 0.28166814, 0.88914692, 0.97647778, 0.16885456,
       0.08158381, 0.54876745, 0.50869432, 0.08792985, 0.57410783,
       0.87977143, 0.81102817, 0.07694593, 0.1481299 , 0.22022789,
       0.1444036 , 0.56512614, 0.08476309, 0.25879495, 0.77213617,
       0.72986305, 0.32818394, 0.97648427, 0.09327976, 0.1253681 ,
       0.90867892, 0.25012304, 0.90320099, 0.35718002, 0.18730

In [26]:
ar4.size

99

In [28]:
ar4=ar4.reshape(11,9)
ar4.size

99

In [29]:
ar4.shape

(11, 9)

In [31]:
ar4=ar4
ar4

array([[0.63616123, 0.95400131, 0.15920392, 0.36337535, 0.83940224,
        0.8281249 , 0.59077329, 0.86857736, 0.2743712 ],
       [0.25314867, 0.55970299, 0.42611381, 0.48412176, 0.51400368,
        0.80154949, 0.31432764, 0.11968132, 0.9501315 ],
       [0.59829699, 0.27849779, 0.61717479, 0.20989132, 0.58311137,
        0.64338021, 0.50683797, 0.68920955, 0.87775963],
       [0.07864126, 0.09897208, 0.24169293, 0.01741263, 0.41230484,
        0.42909468, 0.62298335, 0.79916845, 0.90373792],
       [0.2648025 , 0.59712596, 0.05970648, 0.13267791, 0.45029531,
        0.08409991, 0.99731244, 0.43566161, 0.64825767],
       [0.39501889, 0.28166814, 0.88914692, 0.97647778, 0.16885456,
        0.08158381, 0.54876745, 0.50869432, 0.08792985],
       [0.57410783, 0.87977143, 0.81102817, 0.07694593, 0.1481299 ,
        0.22022789, 0.1444036 , 0.56512614, 0.08476309],
       [0.25879495, 0.77213617, 0.72986305, 0.32818394, 0.97648427,
        0.09327976, 0.1253681 , 0.90867892, 0.25012304],


In [32]:
ar4.shape

(11, 9)

In [33]:
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [34]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [15, 12,  9]])

In [35]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
ar=np.append(ar,10)

In [38]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
ar=np.delete(ar,6,axis=0)
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [40]:
ar=np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [15, 12,  9]])

In [43]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [15, 12,  9]])

In [44]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 15, 12,  9]])

In [45]:
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [15, 12,  9]])]

In [46]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [15, 12,  9]])]

In [47]:
ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
ar6[1]

array([[7, 8, 9],
       [1, 4, 7]])

In [49]:
ar6[2]

array([[ 3,  5,  8],
       [15, 12,  9]])

In [50]:
ar6[0][0][0]

1

Scalar Expressions
add

subtract

multiply

divide

power

In [51]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 15, 12,  9]])

Vector Operations

In [52]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [15, 12,  9]])]

In [53]:
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  9, 13]])

In [54]:
ar8 = np.multiply(ar6[0],ar6[1])
ar8

array([[ 7, 16, 27],
       [ 4, 20, 42]])

In [55]:
ar9 = np.divide(ar6[0],ar6[1])
ar9

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.25      , 0.85714286]])

In [56]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [57]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [58]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

Statistics

In [60]:
np.mean(ar5)

6.055555555555555

In [61]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.        ])

In [62]:
np.median(ar5)

5.5

In [63]:
np.median(ar5,axis=1)

array([2.5, 5. , 9. ])

In [64]:
np.min(ar5)

1

In [65]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [66]:
np.max(ar5,axis=0)

array([ 7,  8,  9, 15, 12,  9])

In [67]:
np.max(ar5,axis=0)
ar5


array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 15, 12,  9]])

In [69]:
ar10=np.array([2,5,3,8,0,4,1,6,9])

ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [70]:
np.argmax(ar10)

8

In [71]:
np.argmin(ar10)

4

In [72]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8], dtype=int64)

In [73]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])